Element wise addition of array, size, Shape

In [7]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])

b=np.array([[7,8,9],[10,11,12]])
print("Addition of a and b is : ",a+b)

print("size of a : ",a.size)

print("shape of a : ",a.shape)

Addition of a and b is :  [[ 8 10 12]
 [14 16 18]]
size of a :  6
shape of a :  (2, 3)


Multiplying a matrix by a scalar

In [3]:
a = np.array([[1,2,3],[4,5,6]])
print("2 * a : ",2*a)

2 * a :  [[ 2  4  6]
 [ 8 10 12]]


Identity Matrix

In [41]:
np.diag(np.array(([1,2,3,4,5])))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [40]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Arange()

In [30]:
print(np.array(np.arange(10)))

print("Multiple of 5 : ",np.arange(5,50,5))

print("Odd numbers between 1 to 100 : ",np.arange(0,101,2))

print("Even numbers between 1 to 100 : ",np.arange(0,100,2))

print("After broadcasting : ",np.arange(0,100,2)+1)

[0 1 2 3 4 5 6 7 8 9]
Multiple of 5 :  [ 5 10 15 20 25 30 35 40 45]
Odd numbers between 1 to 100 :  [  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
Even numbers between 1 to 100 :  [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
After broadcasting :  [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


zeros() and ones()

In [61]:
print("zeros : ",np.zeros((2,3)))

print("ones : ",np.ones(30)+7)

#print(np.full((2, 3), 5))
print("ones 2,3 : ",np.ones((2,3))*5)
print("ones 5,9 : ",np.ones((5,9))+2)

zeros :  [[0. 0. 0.]
 [0. 0. 0.]]
ones :  [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.
 8. 8. 8. 8. 8. 8.]
ones 2,3 :  [[5. 5. 5.]
 [5. 5. 5.]]
ones 5,9 :  [[3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3.]]


random

In [11]:
np.random.random((2,3))

array([[0.52556107, 0.47139391, 0.73208622],
       [0.17266586, 0.0017106 , 0.73696207]])

In [12]:
np.random.normal((5,8))

array([4.08423583, 8.1307033 ])

In [65]:
#Array Generation of random integers within a specified range
np.random.randint(0, 10, size = (5,5))

array([[0, 5, 8, 9, 1],
       [0, 7, 6, 3, 9],
       [1, 2, 9, 7, 9],
       [5, 6, 2, 4, 1],
       [7, 5, 6, 2, 2]])

In [63]:
np.random.normal(loc=1.0, scale=2.0, size=(2,2))

array([[ 0.32057635,  0.26348444],
       [-3.96157579,  1.36127988]])

In [ ]:
#np.savetxt("asave.txt",A)
#save values to given file .. if file not present it create the file

#b = np.loadtxt("asave.txt")
#read value from the given file.. if file not present it gives an error

In [14]:
distance=[45,50,35]
speed=[5,10,7]

distance=np.array(distance)
speed=np.array(speed)
time=distance/speed
print (time)

[9. 5. 5.]


Broadcasting

In [21]:
print("Array a : ",a)
print("Type of a : ",type(a))
print("Multiply whole array with value : ",a*5)
print("Divide wgole array with same value : ",a/5)

Array a :  [[1 2 3]
 [4 5 6]]
Type of a :  <class 'numpy.ndarray'>
Multiply whole array with value :  [[ 5 10 15]
 [20 25 30]]
Divide wgole array with same value :  [[0.2 0.4 0.6]
 [0.8 1.  1.2]]


In [33]:
a=np.arange(24)
print(a.shape)

(24,)


LineSpace()

In [31]:
array2=np.linspace(1,10,10)
print(array2)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [34]:
b=a.reshape(4,3,2)
print(b)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


Slice

In [47]:
a=np.arange(20)
print(a)

print("a[3:] : ",a[3:])

print("a[:3] : ",a[:3])

print("a[3:7] : ",a[3:7])

print("a[3::2] : ",a[3::2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
a[3:] :  [ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
a[:3] :  [0 1 2]
a[3:7] :  [3 4 5 6]
a[3::2] :  [ 3  5  7  9 11 13 15 17 19]


Vstack and Hstack

a1 = np.array([[1,2],
               [3,4],
               [5,6]])

a2 = np.array([[7,8],
               [9,10],
               [10,11]])

print("VSTACK : ",np.vstack((a1, a2)))
print("HSTACK : ",np.hstack((a1,a2)))

In [55]:
print("Firs row : ",o[0:1])
print("First Column : ",o[0:,-4])

Firs row :  [[1 2 7 8]]
First Column :  [1 3 5]


Array Datatype conversion

In [57]:
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

print("Type of A : ",a.astype('int'))

Type of A :  [[2 3 1]
 [4 2 1]]


Boolean Array from Binary Array

In [58]:
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])

print("Boolean array : ",a.astype('bool'))

Boolean array :  [[ True False False]
 [ True  True  True]
 [False False False]]


Getting the positions where elements of 2 arrays match

In [59]:
a = np.array([1,2,3,4,5])

b = np.array([1,3,2,4,5])

print(np.where(a == b))

(array([0, 3, 4]),)


Array Generation by repeatition of a small array across each dimension

In [69]:
a = np.array([[1,2,3],
              [4,5,6]])

print(np.tile(a, 10))

[[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]]


Matrix Multiplication

In [67]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

print("a*b : ",np.matmul(a, b))

a*b :  [[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


Matirx Transpose

In [68]:
print("Transpose of a is : ",a.T)

Transpose of a is :  [[1 4 7]
 [2 5 8]
 [3 6 9]]


Sine and Cosine

In [72]:
angles = np.array([3.14, 3.14/2, 6.28])
print('Sine of the given array of angles = ',np.sin(angles))
print('Cosine of the given array of angles = ',np.cos(angles))

Sine of the given array of angles =  [ 0.00159265  0.99999968 -0.0031853 ]
Cosine of the given array of angles =  [-9.99998732e-01  7.96326711e-04  9.99994927e-01]
